version: 2

jobs:
  ApolloClient:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: cd client && npm ci
      - run: cd client && npm test
      - run: cd client && npx apolloclient:check

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd client && npx apolloclient:push
          fi

  ApolloServer:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: cd server && npm ci
      - run: cd server && npm test

      - run:
          name: Starting server
          command: cd server && npm run start:ci
          background: true

      - run: sleep 5
      - run: cd server && npx apolloservice:check

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd server && npx apolloservice:push
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - ApolloClient
      - ApolloServer
